name: Tests

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test
      - name: Copy report
        run: cp -r build/reports/tests/ testReports
      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: testReports/
