name: Tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        id: test
        continue-on-error: true
        run: ./gradlew --no-build-cache cleanTest test
      - name: Copy report
        if: ${{ failure() }}
        id: copyFail
        continue-on-error: true
        run: cp -r build/reports/tests/ testReports
      - name: Export artifact
        if: ${{ failure() && steps.copyFail.outcome != 'failure' }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: testReports/
