name: Tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        id: test
        run: ./gradlew --no-build-cache cleanTest test
      - name: Collect reports
        if: '!cancelled()'
        run: python .github/workflowHelpers/collect_reports.py testReports
      - name: Export artifact
        if: '!cancelled()'
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: testReports/
